### ISSUE TITLE
django 1.7?

### ISSUE THREAD

**Issue by lingfish** [PeterJohnson/roster#1]
Any chance you'll upgrade this to work on recent versions? It bombs pretty hard.

**Comment by PeterJohnson** [comment]
I'll take a look at it.  There's a larger rewrite in process, but my team is still actively using this version.

**Comment by lingfish** [comment]
Ok, so what version(s) are supported? I had a far few missing pip installs, etc too. 

Was hoping to fire it up as a quick look, due to no screenshots ;)

**Comment by PeterJohnson** [comment]
Also, see https://github.com/team294/roster for the latest version (I should actually delete this repo).  The rewrite doesn't quite have feature parity but is a lot nicer UI wise and is built on Flask rather than Django, see https://github.com/team294/surfmanage

My current install is running on Django 1.4 pre-alpha (yikes, I know).  Specifically svn version 16722.

**Comment by lingfish** [comment]
Nice, thanks.
